// This file is a part of "Candle" application (hjLabs.in fork).
// Copyright 2026 hjLabs.in / Hemang Joshi

#include "gcodeemitter.h"

#include <QtMath>
#include <cmath>

namespace cadcam {

GcodeEmitter::GcodeEmitter(const EmitterOptions &options)
    : m_opt(options)
{
}

QString GcodeEmitter::fmt(double value) const
{
    // Snap values that round to zero so we never emit "-0.000".
    double snap = 0.5 * std::pow(10.0, -m_opt.decimals);
    if (std::fabs(value) < snap)
        value = 0.0;
    return QString::number(value, 'f', m_opt.decimals);
}

QString GcodeEmitter::axisWord(QChar axis, double value) const
{
    return axis + fmt(value);
}

double GcodeEmitter::mapZ(const ToolpathMove &move) const
{
    if (m_opt.zMode == ZMode::Pen)
        return (move.type == MoveType::Rapid) ? m_opt.penUpZ : m_opt.penDownZ;
    return move.target.z();
}

void GcodeEmitter::addLine(QStringList &out, const QString &code, int &lineNo) const
{
    if (code.isEmpty()) return;
    if (m_opt.lineNumbers) {
        out.append(QStringLiteral("N%1 %2").arg(lineNo).arg(code));
        lineNo += m_opt.lineNumberStep;
    } else {
        out.append(code);
    }
}

void GcodeEmitter::emitMove(QStringList &out, const ToolpathMove &move,
                            bool &hasLast, QVector3D &last, int &lastG,
                            double &lastFeed, int &lineNo) const
{
    QVector3D target(move.target.x(), move.target.y(), mapZ(move));

    int g = (move.type == MoveType::Rapid) ? 0 : 1;
    double feed = (move.type == MoveType::Plunge) ? m_opt.feedZ : m_opt.feedXY;

    double tol = 0.5 * std::pow(10.0, -m_opt.decimals);

    bool moveX = !hasLast || std::fabs(target.x() - last.x()) > tol;
    bool moveY = !hasLast || std::fabs(target.y() - last.y()) > tol;
    bool moveZ = !hasLast || std::fabs(target.z() - last.z()) > tol;
    bool hasMotion = moveX || moveY || moveZ;

    // Skip a line that carries no motion and no mode change. Do this BEFORE
    // touching lastFeed, so a skipped line never swallows a pending feed word.
    if (!hasMotion && g == lastG) {
        last = target;
        hasLast = true;
        return;
    }

    QStringList words;
    if (g != lastG)
        words << QStringLiteral("G%1").arg(g);
    if (moveX) words << axisWord('X', target.x());
    if (moveY) words << axisWord('Y', target.y());
    if (moveZ) words << axisWord('Z', target.z());

    // Feed only matters on cutting moves and only when it changes.
    if (g == 1 && std::fabs(feed - lastFeed) > 1e-6) {
        words << (QChar('F') + fmt(feed));
        lastFeed = feed;
    }

    addLine(out, words.join(' '), lineNo);
    lastG = g;
    last = target;
    hasLast = true;
}

QString GcodeEmitter::emitProgram(const Toolpath &path) const
{
    QVector<Toolpath> v;
    v.append(path);
    return emitProgram(v);
}

QString GcodeEmitter::emitProgram(const QVector<Toolpath> &paths) const
{
    QStringList out;
    int lineNo = m_opt.lineNumberStep;
    const double retractZ = (m_opt.zMode == ZMode::Pen) ? m_opt.penUpZ : m_opt.safeZ;

    // ---- Header -----------------------------------------------------------
    if (m_opt.comments && !m_opt.programName.isEmpty())
        out.append(QStringLiteral("(%1)").arg(m_opt.programName));
    if (m_opt.comments)
        out.append(QStringLiteral("(Generated by hjLabs Candle CAD/CAM)"));

    addLine(out, m_opt.metric ? QStringLiteral("G21") : QStringLiteral("G20"),
            lineNo); // units
    addLine(out, QStringLiteral("G90"), lineNo);   // absolute distance
    addLine(out, QStringLiteral("G94"), lineNo);   // feed per minute
    addLine(out, QStringLiteral("G17"), lineNo);   // XY plane

    // Guaranteed safe start: lift Z before any XY travel.
    addLine(out, QStringLiteral("G0 Z%1").arg(fmt(retractZ)), lineNo);

    if (m_opt.useSpindle && m_opt.zMode == ZMode::Spindle) {
        addLine(out, QStringLiteral("M3 S%1").arg(fmt(m_opt.spindleRPM)), lineNo);
        if (m_opt.spindleDwell > 0.0)
            addLine(out, QStringLiteral("G4 P%1").arg(fmt(m_opt.spindleDwell)), lineNo);
    }

    // ---- Body -------------------------------------------------------------
    bool hasLast = false;
    QVector3D last(0, 0, retractZ);
    int lastG = -1;
    double lastFeed = -1.0;

    for (const Toolpath &path : paths) {
        if (path.isEmpty()) continue;
        if (m_opt.comments && !path.name.isEmpty())
            out.append(QStringLiteral("(%1)").arg(path.name));
        for (const ToolpathMove &m : path.moves)
            emitMove(out, m, hasLast, last, lastG, lastFeed, lineNo);
    }

    // ---- Footer -----------------------------------------------------------
    addLine(out, QStringLiteral("G0 Z%1").arg(fmt(retractZ)), lineNo);
    if (m_opt.useSpindle && m_opt.zMode == ZMode::Spindle)
        addLine(out, QStringLiteral("M5"), lineNo);
    addLine(out, QStringLiteral("M30"), lineNo);

    return out.join('\n') + '\n';
}

} // namespace cadcam
