// This file is a part of "Candle" application (hjLabs.in fork).
// Copyright 2026 hjLabs.in / Hemang Joshi

#include "soldering.h"

#include <QStringList>
#include <cmath>

namespace cadcam {

namespace {
QString fmt(double value, int decimals)
{
    double snap = 0.5 * std::pow(10.0, -decimals);
    if (std::fabs(value) < snap) value = 0.0;
    return QString::number(value, 'f', decimals);
}
}

QString SolderingGenerator::generate(const QVector<SolderPoint> &points,
                                     const SolderingParams &p) const
{
    const int d = p.decimals;
    QStringList o;

    // ---- Header ----------------------------------------------------------
    if (!p.programName.isEmpty())
        o << QStringLiteral("(%1)").arg(p.programName);
    o << QStringLiteral("(Generated by hjLabs Candle Auto-Soldering)");
    o << (p.metric ? QStringLiteral("G21") : QStringLiteral("G20"));
    o << QStringLiteral("G90");
    o << QStringLiteral("G94");
    o << QStringLiteral("G17");
    o << QStringLiteral("M5");                                  // feeder off to start
    o << QStringLiteral("G0 Z%1").arg(fmt(p.safeZ, d));         // safe height first

    // ---- Per-point sequences --------------------------------------------
    int n = 0;
    for (const SolderPoint &pt : points) {
        ++n;
        const QString xy = QStringLiteral("G0 X%1 Y%2")
                               .arg(fmt(pt.x, d)).arg(fmt(pt.y, d));
        const QString feedOn = QStringLiteral("M3 S%1").arg(fmt(p.feederRPM, d));
        const QString feed   = QStringLiteral("G4 P%1").arg(fmt(pt.feedSeconds, d));
        const QString touch  = QStringLiteral("G1 Z%1 F%2")
                                   .arg(fmt(pt.touchZ, d)).arg(fmt(p.plungeFeed, d));
        const QString raise  = QStringLiteral("G0 Z%1").arg(fmt(pt.freeZ, d));

        if (pt.type == SolderFeedType::PreSolder) {
            o << QStringLiteral("(Point %1: pre-solder, feed %2s)")
                     .arg(n).arg(fmt(pt.feedSeconds, d));
            o << raise;                                         // ensure raised to free Z
            o << xy;                                            // move above pad at free Z
            o << feedOn;                                        // pre-feed wire onto tip
            o << feed;
            o << QStringLiteral("M5");                          // stop feeder
            o << touch;                                         // touch pad to deposit
            if (p.settleSeconds > 0.0)
                o << QStringLiteral("G4 P%1").arg(fmt(p.settleSeconds, d));
            o << raise;                                         // retract to free Z
        } else { // TouchDown
            o << QStringLiteral("(Point %1: touch-down, feed %2s)")
                     .arg(n).arg(fmt(pt.feedSeconds, d));
            o << raise;                                         // ensure raised to free Z
            o << xy;                                            // move above pad at free Z
            o << touch;                                         // touch pad first
            o << feedOn;                                        // feed wire while in contact
            o << feed;
            o << QStringLiteral("M5");                          // stop feeder
            if (p.settleSeconds > 0.0)
                o << QStringLiteral("G4 P%1").arg(fmt(p.settleSeconds, d));
            o << raise;                                         // retract to free Z
        }
    }

    // ---- Footer ----------------------------------------------------------
    o << QStringLiteral("G0 Z%1").arg(fmt(p.safeZ, d));
    o << QStringLiteral("M5");
    o << QStringLiteral("M30");

    return o.join('\n') + '\n';
}

} // namespace cadcam
