// Laser/CNC framing helper — UI-independent.
// Pure TypeScript: no React/DOM/three.js imports (mirrors the src/core/ split).
//
// "Framing" traces the XY bounding rectangle of a job so the operator can see
// exactly what area will be cut/engraved BEFORE committing to the run. On a
// diode laser the perimeter can be traced at a tiny visible power so a dim dot
// follows the rectangle; otherwise the head just moves around it with the beam
// off. Either way the program is bracketed by `M5 S0` at start and end so the
// laser is guaranteed off whenever it is not deliberately tracing.

import { BBox, Polyline } from './geometry';

/** Formatted number, never "-0.000" — mirrors the emitter / soldering fmt(). */
function fmt(value: number, decimals: number): string {
  const snap = 0.5 * Math.pow(10, -decimals);
  if (Math.abs(value) < snap) value = 0;
  if (value === 0) value = 0; // collapse a residual signed zero
  return value.toFixed(decimals);
}

function clamp(v: number, lo: number, hi: number): number {
  return v < lo ? lo : v > hi ? hi : v;
}

/** Default S-value ceiling (GRBL's $30), matching laserCam. */
const kDefaultSMax = 1000;

/** Options for {@link frameProgram}. */
export interface FrameOptions {
  feed: number; // perimeter feed (mm/min) when tracing at power
  powerPct?: number; // small >0 → trace at low power (G1); 0/undefined → G0 rapids, beam off
  sMax?: number; // S value at 100% (GRBL $30); default 1000
  loops?: number; // repeat the rectangle N times (default 1)
  mode?: 'M3' | 'M4'; // laser on mode when tracing at power (default M3)
  decimals?: number; // coordinate precision (default 3)
  programName?: string; // leading comment
}

/** XY bounding box across all polyline vertices (reuses geometry's BBox). */
export function boundsOf(polylines: Polyline[]): BBox {
  const b = new BBox();
  for (const pl of polylines) for (const p of pl.points) b.expand(p);
  return b;
}

/**
 * Generate a G-code program that walks the machine around the job's XY bounding
 * RECTANGLE: (minX,minY) → (maxX,minY) → (maxX,maxY) → (minX,maxY) → close.
 *
 * If `powerPct` is a small >0 value, the perimeter is traced at that low power
 * with `G1` at `feed` (so a diode laser shows a faint visible tracing dot);
 * otherwise the head moves with `G0` rapids and the laser OFF (motion only).
 * `loops` repeats the rectangle (default 1). The program ALWAYS starts and ends
 * with `M5 S0` so the beam is off before and after the trace. Output is modal,
 * `G21 G90`, and never emits "-0.000". The returned string is streamed to the
 * controller by the UI.
 */
export function frameProgram(bbox: BBox, opts: FrameOptions): string {
  const d = opts.decimals ?? 3;
  const sMax = opts.sMax && opts.sMax > 0 ? opts.sMax : kDefaultSMax;
  const loops = Math.max(1, Math.floor(opts.loops ?? 1));
  const mode = opts.mode ?? 'M3';
  const pct = clamp(opts.powerPct ?? 0, 0, 100);
  const trace = pct > 0; // trace at power (G1) vs move only (G0)
  const sOn = Math.round((pct / 100) * sMax);

  const o: string[] = [];

  if (opts.programName && opts.programName.length > 0) o.push(`(${opts.programName})`);
  o.push('(Generated by karmyogi Framing — traces the XY bounding box)');

  // An invalid/empty bbox yields a safe no-op frame: still bracket with M5 S0.
  if (!bbox.isValid()) {
    o.push('G21');
    o.push('G90');
    o.push('M5 S0');
    o.push('M5');
    o.push('M30');
    return o.join('\n') + '\n';
  }

  const x0 = bbox.min.x;
  const y0 = bbox.min.y;
  const x1 = bbox.max.x;
  const y1 = bbox.max.y;
  // Corner order: BL → BR → TR → TL → back to BL.
  const corners: Array<[number, number]> = [
    [x0, y0],
    [x1, y0],
    [x1, y1],
    [x0, y1],
  ];

  if (trace) {
    o.push(`(Trace at ${fmt(pct, 1)}% -> S${sOn} of ${sMax}, mode ${mode})`);
  } else {
    o.push('(Move only — laser OFF, G0 rapids)');
  }

  // ---- Header -----------------------------------------------------------
  o.push('G21'); // mm
  o.push('G90'); // absolute
  o.push('M5 S0'); // beam OFF at start (safety)

  // Position at the first corner with the beam OFF regardless of mode.
  o.push(`G0 X${fmt(x0, d)} Y${fmt(y0, d)} S0`);
  if (trace) o.push(`${mode} S${sOn}`); // enable the faint tracing beam

  let lastFeed = -1;
  for (let loop = 0; loop < loops; ++loop) {
    if (loops > 1) o.push(`(Loop ${loop + 1} of ${loops})`);
    // From the current corner (BL), walk BR → TR → TL → BL.
    const seq: Array<[number, number]> = [corners[1], corners[2], corners[3], corners[0]];
    for (const [x, y] of seq) {
      if (trace) {
        let line = `G1 X${fmt(x, d)} Y${fmt(y, d)}`;
        if (Math.abs(opts.feed - lastFeed) > 1e-6) {
          line += ` F${fmt(opts.feed, d)}`;
          lastFeed = opts.feed;
        }
        o.push(line);
      } else {
        o.push(`G0 X${fmt(x, d)} Y${fmt(y, d)}`);
      }
    }
  }

  // ---- Footer -----------------------------------------------------------
  if (trace) o.push('S0'); // power to zero before turning off
  o.push('M5'); // laser fully off (safety)
  o.push('M30');

  return o.join('\n') + '\n';
}
