// Automatic-soldering G-code generator — UI-independent.
// Ported from the Qt/C++ reference cadcam/soldering.{h,cpp}.
//
// Machine model: a soldering iron is mounted at the head and the controller's
// spindle on/off output drives a solder-wire FEEDER motor. Turning the
// "spindle" on (M3 S..) runs the feeder; M5 stops it. The amount of wire fed is
// controlled by how long the feeder runs — a dwell (G4 P<seconds>) between M3
// and M5.
//
// Safety behaviour matches the rest of the CAM core: G21/G90/G94/G17 header, a
// guaranteed safe-Z retract before any XY travel and at program end, and number
// formatting that never emits "-0.000".

/** When the solder wire is fed relative to the touch-down. */
export enum SolderFeedType {
  /**
   * Feed wire onto the iron tip while raised, THEN touch the pad to deposit the
   * pre-melted blob.
   */
  PreSolder = 'PreSolder',
  /** Touch the pad FIRST, then feed wire while the tip is in contact. */
  TouchDown = 'TouchDown',
}

/** One soldering action at an absolute machine location. */
export interface SolderPoint {
  x: number;
  y: number;
  /** Raised travel/retract height (mm, absolute). */
  freeZ: number;
  /** Touch-down height where soldering happens (mm, absolute). */
  touchZ: number;
  /** Feed ordering relative to touch-down. */
  type: SolderFeedType;
  /** Feeder ON time (seconds). */
  feedSeconds: number;
}

/** Defaults for a fresh soldering point. */
export function defaultSolderPoint(overrides: Partial<SolderPoint> = {}): SolderPoint {
  return {
    x: 0,
    y: 0,
    freeZ: 5.0,
    touchZ: -1.0,
    type: SolderFeedType.TouchDown,
    feedSeconds: 0.5,
    ...overrides,
  };
}

/** Global generator policy (mirrors C++ SolderingParams). */
export interface SolderingParams {
  metric: boolean; // G21 vs G20
  safeZ: number; // travel/retract height between points (mm)
  feederRPM: number; // emitted as the S word when the feeder runs
  plungeFeed: number; // touch-down feed rate (mm/min)
  settleSeconds: number; // dwell after feeding, before retract (s); 0 = none
  decimals: number;
  programName: string;
}

export function defaultSolderingParams(overrides: Partial<SolderingParams> = {}): SolderingParams {
  return {
    metric: true,
    safeZ: 5.0,
    feederRPM: 1000.0,
    plungeFeed: 100.0,
    settleSeconds: 0.0,
    decimals: 3,
    programName: 'hjLabs Auto-Soldering',
    ...overrides,
  };
}

/** Formatted number, never "-0.000" — mirrors the C++ fmt() and the emitter. */
function fmt(value: number, decimals: number): string {
  const snap = 0.5 * Math.pow(10, -decimals);
  if (Math.abs(value) < snap) value = 0;
  if (value === 0) value = 0; // collapse a residual signed zero
  return value.toFixed(decimals);
}

/**
 * Produce a complete, safe G-code program for the given soldering points.
 * Faithful port of cadcam::SolderingGenerator::generate.
 */
export function generateSoldering(points: SolderPoint[], params: Partial<SolderingParams> = {}): string {
  const p = defaultSolderingParams(params);
  const d = p.decimals;
  const o: string[] = [];

  // ---- Header -----------------------------------------------------------
  if (p.programName.length > 0) o.push(`(${p.programName})`);
  o.push('(Generated by hjLabs Candle Auto-Soldering)');
  o.push(p.metric ? 'G21' : 'G20');
  o.push('G90');
  o.push('G94');
  o.push('G17');
  o.push('M5'); // feeder off to start
  o.push(`G0 Z${fmt(p.safeZ, d)}`); // safe height first

  // ---- Per-point sequences ----------------------------------------------
  let n = 0;
  for (const pt of points) {
    ++n;
    const xy = `G0 X${fmt(pt.x, d)} Y${fmt(pt.y, d)}`;
    const feedOn = `M3 S${fmt(p.feederRPM, d)}`;
    const feed = `G4 P${fmt(pt.feedSeconds, d)}`;
    const touch = `G1 Z${fmt(pt.touchZ, d)} F${fmt(p.plungeFeed, d)}`;
    const raise = `G0 Z${fmt(pt.freeZ, d)}`;

    if (pt.type === SolderFeedType.PreSolder) {
      o.push(`(Point ${n}: pre-solder, feed ${fmt(pt.feedSeconds, d)}s)`);
      o.push(raise); // ensure raised to free Z
      o.push(xy); // move above pad at free Z
      o.push(feedOn); // pre-feed wire onto tip
      o.push(feed);
      o.push('M5'); // stop feeder
      o.push(touch); // touch pad to deposit
      if (p.settleSeconds > 0.0) o.push(`G4 P${fmt(p.settleSeconds, d)}`);
      o.push(raise); // retract to free Z
    } else {
      // TouchDown
      o.push(`(Point ${n}: touch-down, feed ${fmt(pt.feedSeconds, d)}s)`);
      o.push(raise); // ensure raised to free Z
      o.push(xy); // move above pad at free Z
      o.push(touch); // touch pad first
      o.push(feedOn); // feed wire while in contact
      o.push(feed);
      o.push('M5'); // stop feeder
      if (p.settleSeconds > 0.0) o.push(`G4 P${fmt(p.settleSeconds, d)}`);
      o.push(raise); // retract to free Z
    }
  }

  // ---- Footer -----------------------------------------------------------
  o.push(`G0 Z${fmt(p.safeZ, d)}`);
  o.push('M5');
  o.push('M30');

  return o.join('\n') + '\n';
}
